CREATE TABLE "University" (
  "university_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "contact_email" varchar(100),
  "contact_phone" varchar(20),
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "Campus" (
  "campus_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "address" text NOT NULL,
  "university_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "Zone" (
  "zone_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text,
  "campus_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "ParkingSpace" (
  "parking_space_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "number" varchar(20) NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'available',
  "zone_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "Role" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(50) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "User" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_number" varchar(20),
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "phone" varchar(20),
  "role_id" int NOT NULL,
  "university_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "active" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "UserCredentials" (
  "credential_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "salt" varchar(100) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "AuthProvider" (
  "provider_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(50) NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "ExternalUserAuthentication" (
  "authentication_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "provider_id" int NOT NULL,
  "external_id" varchar(255) NOT NULL,
  "provider_email" varchar(100),
  "access_token" varchar(255),
  "refresh_token" varchar(255),
  "linked_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "last_login" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "VehicleType" (
  "vehicle_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(50) NOT NULL,
  "description" text,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "LicensePlate" (
  "license_plate_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "plate_number" varchar(20) NOT NULL,
  "user_id" int NOT NULL,
  "vehicle_type_id" int NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "UnknownLicensePlateRecord" (
  "record_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "plate_number" varchar(20) NOT NULL,
  "timestamp" timestamp NOT NULL,
  "image_url" text,
  "campus_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "ParkingPreference" (
  "preference_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "zone_id" int NOT NULL,
  "start_time" time,
  "end_time" time,
  "notify" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "AccessPermission" (
  "access_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "campus_id" int NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "ParkingSession" (
  "session_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "parking_space_id" int NOT NULL,
  "license_plate_id" int,
  "entry_time" timestamp NOT NULL,
  "exit_time" timestamp,
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE INDEX ON "Campus" ("university_id");

CREATE INDEX ON "Zone" ("campus_id");

CREATE INDEX ON "ParkingSpace" ("zone_id", "status");

CREATE INDEX ON "ParkingSpace" ("status");

CREATE INDEX ON "User" ("email");

CREATE INDEX ON "User" ("role_id");

CREATE INDEX ON "User" ("university_id");

CREATE INDEX ON "UserCredentials" ("user_id");

CREATE UNIQUE INDEX ON "ExternalUserAuthentication" ("user_id", "provider_id");

CREATE UNIQUE INDEX ON "ExternalUserAuthentication" ("provider_id", "external_id");

CREATE INDEX ON "ExternalUserAuthentication" ("user_id");

CREATE INDEX ON "ExternalUserAuthentication" ("provider_id");

CREATE INDEX ON "LicensePlate" ("plate_number");

CREATE INDEX ON "LicensePlate" ("user_id");

CREATE INDEX ON "LicensePlate" ("vehicle_type_id");

CREATE INDEX ON "UnknownLicensePlateRecord" ("plate_number");

CREATE INDEX ON "UnknownLicensePlateRecord" ("campus_id");

CREATE INDEX ON "UnknownLicensePlateRecord" ("timestamp");

CREATE INDEX ON "ParkingPreference" ("user_id");

CREATE INDEX ON "ParkingPreference" ("zone_id");

CREATE INDEX ON "AccessPermission" ("user_id");

CREATE INDEX ON "AccessPermission" ("campus_id");

CREATE INDEX ON "AccessPermission" ("start_date", "end_date");

CREATE INDEX ON "ParkingSession" ("parking_space_id");

CREATE INDEX ON "ParkingSession" ("license_plate_id");

CREATE INDEX ON "ParkingSession" ("status");

CREATE INDEX ON "ParkingSession" ("entry_time");

CREATE INDEX ON "ParkingSession" ("exit_time");

COMMENT ON TABLE "ParkingSpace" IS 'status should be one of: ''available'', ''occupied'', ''reserved'', ''maintenance''';

COMMENT ON TABLE "Role" IS 'Examples: ''student'', ''administrative'', ''guest'', ''admin''';

COMMENT ON TABLE "VehicleType" IS 'Examples: ''car'', ''motorcycle'', ''bicycle'', ''truck'', etc.';

COMMENT ON TABLE "ParkingSession" IS 'status should be one of: ''active'', ''completed'', ''cancelled''';

ALTER TABLE "Campus" ADD FOREIGN KEY ("university_id") REFERENCES "University" ("university_id");

ALTER TABLE "Zone" ADD FOREIGN KEY ("campus_id") REFERENCES "Campus" ("campus_id");

ALTER TABLE "ParkingSpace" ADD FOREIGN KEY ("zone_id") REFERENCES "Zone" ("zone_id");

ALTER TABLE "User" ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("role_id");

ALTER TABLE "User" ADD FOREIGN KEY ("university_id") REFERENCES "University" ("university_id");

ALTER TABLE "UserCredentials" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "ExternalUserAuthentication" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "ExternalUserAuthentication" ADD FOREIGN KEY ("provider_id") REFERENCES "AuthProvider" ("provider_id");

ALTER TABLE "LicensePlate" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "LicensePlate" ADD FOREIGN KEY ("vehicle_type_id") REFERENCES "VehicleType" ("vehicle_type_id");

ALTER TABLE "UnknownLicensePlateRecord" ADD FOREIGN KEY ("campus_id") REFERENCES "Campus" ("campus_id");

ALTER TABLE "ParkingPreference" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "ParkingPreference" ADD FOREIGN KEY ("zone_id") REFERENCES "Zone" ("zone_id");

ALTER TABLE "AccessPermission" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "AccessPermission" ADD FOREIGN KEY ("campus_id") REFERENCES "Campus" ("campus_id");

ALTER TABLE "ParkingSession" ADD FOREIGN KEY ("parking_space_id") REFERENCES "ParkingSpace" ("parking_space_id");

ALTER TABLE "ParkingSession" ADD FOREIGN KEY ("license_plate_id") REFERENCES "LicensePlate" ("license_plate_id");

-- DML
INSERT INTO "University" ("name", "contact_email", "contact_phone") VALUES
('Tecnológico Nacional de México en Celaya', 'direccion@itcelaya.edu.mx', '4616625100');

INSERT INTO "Campus" ("name", "address", "university_id") VALUES
('Campus 1', 'Antonio García Cubas Pte #600 esq. Av. Tecnológico Celaya, Gto.', 1),
('Campus 2', 'Antonio García Cubas 1200, Alfredo Vazquez Bonfil, 38010 Celaya, Gto.', 1);

INSERT INTO "Zone" ("name", "description", "campus_id") VALUES
('Zone G', 'Systems building parking area', 2),
('Zone H', 'Center for the arts parking area', 2);

INSERT INTO "ParkingSpace" ("number", "status", "zone_id") VALUES
('G1', 'available', 1),
('G2', 'available', 1),
('G3', 'available', 1),
('H1', 'available', 2),
('H2', 'available', 2),
('H3', 'available', 2);
-- note: status should be one of: 'available', 'occupied', 'reserved', 'maintenance'

INSERT INTO "Role" ("name") VALUES ('Student'), ('Teacher'), ('Administrative'), ('Guest'), ('Admin');
-- note: Examples: 'student', 'administrative', 'guest', 'admin'
